SENSOR_ERROR = 'SENSOR_ERROR'

PIT_ANALYSING = 'PIT_ANALYSING'
PIT_HEATING = 'PIT_HEATING'
PIT_UP_TO_TEMP = 'PIT_UP_TO_TEMP'
PIT_OVER_TEMP = 'PIT_OVER_TEMP'
PIT_LID_OPEN = 'PIT_LID_OPEN'
PIT_FLAME_OUT = 'PIT_FLAME_OUT'

PROBE_ANALYSING = 'PROBE_ANALYSING'
PROBE_UNDER_SETPOINT = 'PROBE_UNDER_SETPOINT'
PROBE_REACHED_SETPOINT = 'PROBE_REACHED_SETPOINT'
PROBE_REACHED_SETPOINT_ALARM = 'PROBE_REACHED_SETPOINT_ALARM'
